### ISSUE TITLE
jreen-9999.ebuild

### ISSUE THREAD

**Issue by bober2000** [Hamper/hamper-overlay#3]
When trying to install =net-im/qutim-9999 got a problem with installing net-libs/jreen-9999 on dodoc as no README file included

**Comment by bober2000** [comment]
diff --git a/net-libs/jreen/Manifest b/net-libs/jreen/Manifest
index c4f9bea..8a0f0fa 100644
--- a/net-libs/jreen/Manifest
+++ b/net-libs/jreen/Manifest
@@ -1 +1 @@
-EBUILD jreen-9999.ebuild 806 SHA256 2531656a6518bc71ee4e02b89eb424f5a9fdaf98430b8d6300b92325ae941e20 SHA512 c4155ab26daa70470734fa5e423d3a7ab494f83bdb2490d3c21ef200fd3db0e3dcd43c0774b4efc0940f6debea54e61c245b7cd88f0cc537a4781f3139231ddf WHIRLPOOL 8ff1190bfaa1c616b5218c817615ffd10dbfebd72345c627c930914f2feced2e7faedaa97851917a1ff6719c8782f6b79e2e376393b0bb5a53dcd1a797fa1537
+EBUILD jreen-9999.ebuild 799 SHA256 d2c1932a0afd24b9d96e904087627bd15e44be36bed42ef1d788cc6d492d4fde SHA512 b7e352bf1ed0739f15333a68c8ab015c83bba72340fd03ab9fb816bc6511823a106c11e218f50421db5e515287ad78d960207ff595cf7edaa0e4d9c5e8208f45 WHIRLPOOL a8b1476684e5bd1ff3d07c105453415f38ddc8f21a468499f2d09feeca10e0ef6a4701622ed3b1b055ab3847b3bbfd21c076523c9236410772852c4801057f23
diff --git a/net-libs/jreen/jreen-9999.ebuild b/net-libs/jreen/jreen-9999.ebuild
index 9a5e30d..1fab950 100644
--- a/net-libs/jreen/jreen-9999.ebuild
+++ b/net-libs/jreen/jreen-9999.ebuild
@@ -31,4 +31,4 @@ DEPEND="
 "
 RDEPEND="${DEPEND}"
 
-DOCS=( AUTHORS ChangeLog README )
+DOCS=( AUTHORS ChangeLog )

**Comment by bober2000** [comment]
Patch solved problem for me

**Comment by Hamper** [comment]
thanks, fixed
